3 4 views
thinknetica-django-lab-02/rudotcom pull request #30
Opened 2021-03-31 14:28 UTC by rudotcom

Closes #21

2021-04-01 13:20 UTC, morgangt requested changes

2021-04-01 13:20 UTC, morgangt commented on ecommerce/main/views.py
> +    pass
если добавляем пустые view давайте опишем к ним docstring

2021-04-01 13:20 UTC, morgangt commented on ecommerce/templates/base.html
> +  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous
свойство integrity и crossorigin можно удалить, или можно оставить

2021-04-01 13:20 UTC, morgangt commented on ecommerce/templates/base.html
> +            </nav>
этот блок лучше вынести в отдельный файл menu.html/nav.html
так будет более структурирование

2021-04-01 14:41 UTC, rudotcom commented on ecommerce/templates/base.html
> +            </nav>
Да, уже вынес в одной из следующих веток

2021-04-01 14:47 UTC, rudotcom commented on ecommerce/templates/base.html
> +  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous
Удалил. Не знаю, что они значат

2021-04-02 21:30 UTC, morgangt approved these changes

2021-04-02 22:08 UTC, merged