4 5 image fields
thinknetica-django-lab-02/rudotcom pull request #36
Opened 2021-04-02 18:37 UTC by rudotcom

Closes #27

2021-04-02 21:14 UTC, morgangt requested changes
файлы из папки  ecommerce/media/ не должны попадать в репозиторий

2021-04-02 21:17 UTC, morgangt requested changes
файлы из папки ecommerce/media/ не должны попадать в репозиторий

2021-04-05 17:57 UTC, morgangt requested changes
ряд функци надо убрать из models.py

2021-04-05 17:57 UTC, morgangt commented on ecommerce/main/models.py
> +    return f'avatar/{filename}'
эти функции и константы надо отнести в один из классов или в файл utils.py

2021-04-06 10:35 UTC, rudotcom commented
Я перенес их в текущем на этот момент PR - 5.2

2021-04-06 10:35 UTC, closed without merging