initial commit
thinknetica-django-lab-02/rudotcom pull request #9
Opened 2021-03-22 17:37 UTC by rudotcom

Blank project

2021-03-23 08:48 UTC, morgangt requested changes

2021-03-23 08:48 UTC, morgangt commented on .gitignore
> +.idea
надо добавить, папку .idea/
в этой папке хранятся настройки редактора.

2021-03-23 09:45 UTC, rudotcom commented on .gitignore
> +.idea
По инструкции к заданию я добавил .idea - это неправильно?

2021-03-24 16:01 UTC, morgangt commented on .gitignore
> +.idea
надо добавить .idea/  и папку venv/

2021-03-24 17:25 UTC, merged